# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QFrame, QHBoxLayout, QLCDNumber, QLabel,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QWidget)

from mplwidget import MplWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(916, 957)
        self.actionCopyright = QAction(MainWindow)
        self.actionCopyright.setObjectName(u"actionCopyright")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.spinBox_leftup_x = QSpinBox(self.centralwidget)
        self.spinBox_leftup_x.setObjectName(u"spinBox_leftup_x")
        self.spinBox_leftup_x.setEnabled(False)
        self.spinBox_leftup_x.setGeometry(QRect(40, 240, 61, 22))
        self.spinBox_leftup_x.setMaximum(9999)
        self.spinBox_leftup_y = QSpinBox(self.centralwidget)
        self.spinBox_leftup_y.setObjectName(u"spinBox_leftup_y")
        self.spinBox_leftup_y.setEnabled(False)
        self.spinBox_leftup_y.setGeometry(QRect(110, 240, 61, 22))
        self.spinBox_leftup_y.setMaximum(9999)
        self.spinBox_rightdown_y = QSpinBox(self.centralwidget)
        self.spinBox_rightdown_y.setObjectName(u"spinBox_rightdown_y")
        self.spinBox_rightdown_y.setEnabled(False)
        self.spinBox_rightdown_y.setGeometry(QRect(780, 680, 71, 22))
        self.spinBox_rightdown_y.setMaximum(9999)
        self.spinBox_rightdown_x = QSpinBox(self.centralwidget)
        self.spinBox_rightdown_x.setObjectName(u"spinBox_rightdown_x")
        self.spinBox_rightdown_x.setEnabled(False)
        self.spinBox_rightdown_x.setGeometry(QRect(700, 680, 61, 22))
        self.spinBox_rightdown_x.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.spinBox_rightdown_x.setAccelerated(True)
        self.spinBox_rightdown_x.setMaximum(9999)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 220, 53, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 220, 53, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(700, 660, 53, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(780, 660, 53, 16))
        self.pushButton_crop = QPushButton(self.centralwidget)
        self.pushButton_crop.setObjectName(u"pushButton_crop")
        self.pushButton_crop.setGeometry(QRect(580, 870, 75, 24))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(666, 870, 118, 23))
        self.progressBar.setValue(0)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(110, 100, 700, 26))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_choose = QPushButton(self.layoutWidget)
        self.pushButton_choose.setObjectName(u"pushButton_choose")

        self.horizontalLayout.addWidget(self.pushButton_choose)

        self.label_path = QLabel(self.layoutWidget)
        self.label_path.setObjectName(u"label_path")
        self.label_path.setMinimumSize(QSize(600, 0))

        self.horizontalLayout.addWidget(self.label_path)

        self.pushButton_rotate_shun = QPushButton(self.centralwidget)
        self.pushButton_rotate_shun.setObjectName(u"pushButton_rotate_shun")
        self.pushButton_rotate_shun.setGeometry(QRect(480, 150, 91, 24))
        self.pushButton_rotate_shun.setAutoRepeat(True)
        self.pushButton_rotate_ni = QPushButton(self.centralwidget)
        self.pushButton_rotate_ni.setObjectName(u"pushButton_rotate_ni")
        self.pushButton_rotate_ni.setGeometry(QRect(290, 150, 91, 24))
        self.pushButton_rotate_ni.setCheckable(False)
        self.pushButton_rotate_ni.setAutoRepeat(True)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(60, 130, 751, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(60, 170, 741, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(106, 730, 711, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(106, 820, 711, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.lcdNumber = QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(400, 150, 64, 23))
        self.lcdNumber.setAutoFillBackground(True)
        self.lcdNumber.setStyleSheet(u"")
        self.lcdNumber.setFrameShape(QFrame.Box)
        self.lcdNumber.setFrameShadow(QFrame.Plain)
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setMode(QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(240, 760, 111, 22))
        self.horizontalSlider = QSlider(self.centralwidget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setEnabled(True)
        self.horizontalSlider.setGeometry(QRect(440, 760, 160, 22))
        self.horizontalSlider.setMouseTracking(True)
        self.horizontalSlider.setValue(20)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksAbove)
        self.label_adjustpara = QLabel(self.centralwidget)
        self.label_adjustpara.setObjectName(u"label_adjustpara")
        self.label_adjustpara.setGeometry(QRect(380, 760, 53, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(620, 760, 51, 21))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShape(QFrame.Panel)
        self.label_5.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(60, 80, 751, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.spinBox_initialtime = QSpinBox(self.centralwidget)
        self.spinBox_initialtime.setObjectName(u"spinBox_initialtime")
        self.spinBox_initialtime.setGeometry(QRect(190, 50, 61, 22))
        self.spinBox_endtime = QSpinBox(self.centralwidget)
        self.spinBox_endtime.setObjectName(u"spinBox_endtime")
        self.spinBox_endtime.setGeometry(QRect(320, 50, 61, 22))
        self.spinBox_interval = QSpinBox(self.centralwidget)
        self.spinBox_interval.setObjectName(u"spinBox_interval")
        self.spinBox_interval.setGeometry(QRect(450, 50, 61, 22))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 50, 41, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(280, 50, 41, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(410, 50, 53, 16))
        self.pushButton_extract = QPushButton(self.centralwidget)
        self.pushButton_extract.setObjectName(u"pushButton_extract")
        self.pushButton_extract.setGeometry(QRect(690, 50, 75, 24))
        self.progressBar_video = QProgressBar(self.centralwidget)
        self.progressBar_video.setObjectName(u"progressBar_video")
        self.progressBar_video.setGeometry(QRect(780, 50, 118, 23))
        self.progressBar_video.setValue(0)
        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(110, 20, 683, 26))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton_video = QPushButton(self.layoutWidget1)
        self.pushButton_video.setObjectName(u"pushButton_video")
        self.pushButton_video.setCheckable(False)
        self.pushButton_video.setChecked(False)

        self.horizontalLayout_2.addWidget(self.pushButton_video)

        self.label_videopath = QLabel(self.layoutWidget1)
        self.label_videopath.setObjectName(u"label_videopath")
        self.label_videopath.setMinimumSize(QSize(600, 0))

        self.horizontalLayout_2.addWidget(self.label_videopath)

        self.spinBox_quality = QSpinBox(self.centralwidget)
        self.spinBox_quality.setObjectName(u"spinBox_quality")
        self.spinBox_quality.setGeometry(QRect(600, 50, 51, 22))
        self.spinBox_quality.setMaximum(100)
        self.spinBox_quality.setValue(100)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(540, 50, 53, 16))
        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(360, 190, 182, 23))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_10 = QLabel(self.layoutWidget2)
        self.label_10.setObjectName(u"label_10")

        self.horizontalLayout_3.addWidget(self.label_10)

        self.spinBox_No = QSpinBox(self.layoutWidget2)
        self.spinBox_No.setObjectName(u"spinBox_No")
        self.spinBox_No.setMinimumSize(QSize(40, 0))
        self.spinBox_No.setMinimum(1)
        self.spinBox_No.setMaximum(999)

        self.horizontalLayout_3.addWidget(self.spinBox_No)

        self.label_11 = QLabel(self.layoutWidget2)
        self.label_11.setObjectName(u"label_11")

        self.horizontalLayout_3.addWidget(self.label_11)

        self.pushButton_preview = QPushButton(self.centralwidget)
        self.pushButton_preview.setObjectName(u"pushButton_preview")
        self.pushButton_preview.setGeometry(QRect(540, 190, 75, 24))
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setObjectName(u"MplWidget")
        self.MplWidget.setGeometry(QRect(180, 220, 500, 500))
        self.label_leftupx = QLabel(self.centralwidget)
        self.label_leftupx.setObjectName(u"label_leftupx")
        self.label_leftupx.setGeometry(QRect(40, 280, 53, 16))
        self.label_leftupx.setFrameShape(QFrame.Panel)
        self.label_leftupx.setFrameShadow(QFrame.Sunken)
        self.label_leftupy = QLabel(self.centralwidget)
        self.label_leftupy.setObjectName(u"label_leftupy")
        self.label_leftupy.setGeometry(QRect(110, 280, 53, 16))
        self.label_leftupy.setFrameShape(QFrame.Panel)
        self.label_leftupy.setFrameShadow(QFrame.Sunken)
        self.label_rightdownx = QLabel(self.centralwidget)
        self.label_rightdownx.setObjectName(u"label_rightdownx")
        self.label_rightdownx.setGeometry(QRect(700, 710, 53, 16))
        self.label_rightdownx.setFrameShape(QFrame.Panel)
        self.label_rightdownx.setFrameShadow(QFrame.Sunken)
        self.label_rightdowny = QLabel(self.centralwidget)
        self.label_rightdowny.setObjectName(u"label_rightdowny")
        self.label_rightdowny.setGeometry(QRect(780, 710, 53, 16))
        self.label_rightdowny.setFrameShape(QFrame.Panel)
        self.label_rightdowny.setFrameShadow(QFrame.Sunken)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(200, 190, 141, 20))
        self.pushButton_refresh = QPushButton(self.centralwidget)
        self.pushButton_refresh.setObjectName(u"pushButton_refresh")
        self.pushButton_refresh.setGeometry(QRect(710, 560, 75, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.spinBox_leftup_x.raise_()
        self.spinBox_leftup_y.raise_()
        self.spinBox_rightdown_y.raise_()
        self.spinBox_rightdown_x.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_crop.raise_()
        self.progressBar.raise_()
        self.layoutWidget.raise_()
        self.pushButton_rotate_shun.raise_()
        self.pushButton_rotate_ni.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.lcdNumber.raise_()
        self.comboBox.raise_()
        self.horizontalSlider.raise_()
        self.label_adjustpara.raise_()
        self.label_5.raise_()
        self.line_5.raise_()
        self.spinBox_initialtime.raise_()
        self.spinBox_endtime.raise_()
        self.spinBox_interval.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.pushButton_extract.raise_()
        self.progressBar_video.raise_()
        self.spinBox_quality.raise_()
        self.label_9.raise_()
        self.pushButton_preview.raise_()
        self.MplWidget.raise_()
        self.label_leftupx.raise_()
        self.label_leftupy.raise_()
        self.label_rightdownx.raise_()
        self.label_rightdowny.raise_()
        self.checkBox.raise_()
        self.pushButton_refresh.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 916, 22))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.pushButton_choose, self.spinBox_leftup_x)
        QWidget.setTabOrder(self.spinBox_leftup_x, self.spinBox_leftup_y)
        QWidget.setTabOrder(self.spinBox_leftup_y, self.spinBox_rightdown_x)
        QWidget.setTabOrder(self.spinBox_rightdown_x, self.spinBox_rightdown_y)
        QWidget.setTabOrder(self.spinBox_rightdown_y, self.pushButton_crop)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.actionCopyright)

        self.retranslateUi(MainWindow)
        self.horizontalSlider.valueChanged.connect(self.label_5.setNum)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"VideoFC", None))
        self.actionCopyright.setText(QCoreApplication.translate("MainWindow", u"Copyright", None))
#if QT_CONFIG(tooltip)
        self.actionCopyright.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>www.asgeologeekfan.top</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u5de6\u4e0aX", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5de6\u4e0aY", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u53f3\u4e0bX", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u53f3\u4e0bY", None))
        self.pushButton_crop.setText(QCoreApplication.translate("MainWindow", u"\u88c1\u526a", None))
        self.pushButton_choose.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u56fe\u7247\u6587\u4ef6\u5939", None))
        self.label_path.setText("")
        self.pushButton_rotate_shun.setText(QCoreApplication.translate("MainWindow", u"\u987a\u65f6\u9488\u65cb\u8f6c1\u00b0", None))
        self.pushButton_rotate_ni.setText(QCoreApplication.translate("MainWindow", u"\u9006\u65f6\u9488\u65cb\u8f6c1\u00b0", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u539f\u59cb\u5f69\u56fe", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7070\u5ea6\u5904\u7406", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u4e8c\u503c\u5316\u5904\u7406", None))

        self.label_adjustpara.setText(QCoreApplication.translate("MainWindow", u"\u4eae\u5ea6", None))
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u8d77\u59cb\u79d2", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u7ec8\u6b62\u79d2", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u95f4\u9694\u79d2", None))
        self.pushButton_extract.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u53d6", None))
        self.pushButton_video.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u89c6\u9891", None))
        self.label_videopath.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u8d28\u91cf", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u6b63\u5728\u9884\u89c8    \u7b2c", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u5f20", None))
        self.pushButton_preview.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u9884\u89c8\u56fe", None))
        self.label_leftupx.setText("")
        self.label_leftupy.setText("")
        self.label_rightdownx.setText("")
        self.label_rightdowny.setText("")
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u624b\u52a8\u8f93\u5165\u88c1\u526a\u6846\u5750\u6807", None))
        self.pushButton_refresh.setText(QCoreApplication.translate("MainWindow", u"\u5237\u65b0\u89c6\u56fe", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
    # retranslateUi

